// <auto-generated />
using System;
using Actividad17.Server.Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Actividad17.Server.Migrations
{
    [DbContext(typeof(ContextoLimpieza))]
    [Migration("20230528224137_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Actividad17.Shared.Models.Clientes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Domicilio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Actividad17.Shared.Models.Garantias", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaG")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ServiciosId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Vigencia")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ServiciosId");

                    b.ToTable("Garantias");
                });

            modelBuilder.Entity("Actividad17.Shared.Models.Servicios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClientesId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClientesId");

                    b.ToTable("Servicios");
                });

            modelBuilder.Entity("Actividad17.Shared.Models.Garantias", b =>
                {
                    b.HasOne("Actividad17.Shared.Models.Servicios", "Servicios")
                        .WithMany("Garantias")
                        .HasForeignKey("ServiciosId");

                    b.Navigation("Servicios");
                });

            modelBuilder.Entity("Actividad17.Shared.Models.Servicios", b =>
                {
                    b.HasOne("Actividad17.Shared.Models.Clientes", "Clientes")
                        .WithMany("Servicios")
                        .HasForeignKey("ClientesId");

                    b.Navigation("Clientes");
                });

            modelBuilder.Entity("Actividad17.Shared.Models.Clientes", b =>
                {
                    b.Navigation("Servicios");
                });

            modelBuilder.Entity("Actividad17.Shared.Models.Servicios", b =>
                {
                    b.Navigation("Garantias");
                });
#pragma warning restore 612, 618
        }
    }
}
